CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

CREATE TABLE genres (
    "Name" text NOT NULL
);

CREATE TABLE movies (
                        "Id" uuid NOT NULL,
                        "Title" text NOT NULL,
                        "ReleaseYear" integer NOT NULL,
                        "Story" text NOT NULL,
                        "Ratings" double precision NOT NULL,
                        "MovieImage" text NULL,
                        "Genre" text NULL,
                        CONSTRAINT "PK_movies" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230725072707_InitialMigrations', '7.0.9');

COMMIT;

START TRANSACTION;

ALTER TABLE movies ADD "DateOfCreation" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230725113431_AddMovieDateOfCreation', '7.0.9');

COMMIT;

START TRANSACTION;

ALTER TABLE movies ADD "TrailerUrl" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230726115406_AddMovieTrailerUrl', '7.0.9');

COMMIT;

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
                               "Id" text NOT NULL,
                               "Name" character varying(256) NULL,
                               "NormalizedName" character varying(256) NULL,
                               "ConcurrencyStamp" text NULL,
                               CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
                               "Id" text NOT NULL,
                               "UserName" character varying(256) NULL,
                               "NormalizedUserName" character varying(256) NULL,
                               "Email" character varying(256) NULL,
                               "NormalizedEmail" character varying(256) NULL,
                               "EmailConfirmed" boolean NOT NULL,
                               "PasswordHash" text NULL,
                               "SecurityStamp" text NULL,
                               "ConcurrencyStamp" text NULL,
                               "PhoneNumber" text NULL,
                               "PhoneNumberConfirmed" boolean NOT NULL,
                               "TwoFactorEnabled" boolean NOT NULL,
                               "LockoutEnd" timestamp with time zone NULL,
                               "LockoutEnabled" boolean NOT NULL,
                               "AccessFailedCount" integer NOT NULL,
                               CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE users (
                       "UserName" text NOT NULL,
                       "EmailAddress" text NOT NULL,
                       "Role" text NOT NULL,
                       "Password" text NOT NULL,
                       CONSTRAINT "PK_users" PRIMARY KEY ("UserName")
);

CREATE TABLE "AspNetRoleClaims" (
                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                    "RoleId" text NOT NULL,
                                    "ClaimType" text NULL,
                                    "ClaimValue" text NULL,
                                    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                                    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE C
                                        ASCADE
);

CREATE TABLE "AspNetUserClaims" (
                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                    "UserId" text NOT NULL,
                                    "ClaimType" text NULL,
                                    "ClaimValue" text NULL,
                                    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                                    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE C
                                        ASCADE
);

CREATE TABLE "AspNetUserLogins" (
                                    "LoginProvider" text NOT NULL,
                                    "ProviderKey" text NOT NULL,
                                    "ProviderDisplayName" text NULL,
                                    "UserId" text NOT NULL,
                                    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                                    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE C
                                        ASCADE
);

CREATE TABLE "AspNetUserRoles" (
                                   "UserId" text NOT NULL,
                                   "RoleId" text NOT NULL,
                                   CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                                   CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CA
                                       SCADE,
                                   CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CA
                                       SCADE
);

CREATE TABLE "AspNetUserTokens" (
                                    "UserId" text NOT NULL,
                                    "LoginProvider" text NOT NULL,
                                    "Name" text NOT NULL,
                                    "Value" text NULL,
                                    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                                    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE C
                                        ASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230815092526_UserModel', '7.0.9');

COMMIT;

START TRANSACTION;

ALTER TABLE users ADD "Badge" text NOT NULL DEFAULT '';

ALTER TABLE users ADD "Rates" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230816110704_UpdateUser', '7.0.9');

COMMIT;
